### ISSUE TITLE
files from stok ROM

### ISSUE THREAD

**Issue by lopestom** [Harlock1978/Armor_11_5G#1]
These files already need? Help in anything?
https://github.com/Harlock1978/Armor_11_5G/blob/b5159e885655e4f6b21b483adcb085b8fc6cb4b5/recovery/root/vendor/etc/vintf/manifest/android.hardware.neuralnetworks%401.2-service-neuron-ann.xml#L1

https://github.com/Harlock1978/Armor_11_5G/blob/a55ffe9d456c78cfdf57bacb625db1b3fae30d3a/recovery/root/vendor/etc/vintf/manifest/vendor.mediatek.hardware.dplanner%402.0-service.xml#L1

If file "old" or not used so delete file: https://github.com/Harlock1978/Armor_11_5G/blob/a55ffe9d456c78cfdf57bacb625db1b3fae30d3a/recovery/root/ueventd.rc.old

**Comment by Harlock1978** [comment]
I copied the whole directory but looking inside them I think that I don't need 

> [Armor_11_5G/recovery/root/vendor/etc/vintf/manifest/android.hardware.neuralnetworks@1.2-service-neuron-ann.xml](https://github.com/Harlock1978/Armor_11_5G/blob/b5159e885655e4f6b21b483adcb085b8fc6cb4b5/recovery/root/vendor/etc/vintf/manifest/android.hardware.neuralnetworks%401.2-service-neuron-ann.xml#L1)
> 

> [Armor_11_5G/recovery/root/vendor/etc/vintf/manifest/vendor.mediatek.hardware.dplanner@2.0-service.xml](https://github.com/Harlock1978/Armor_11_5G/blob/a55ffe9d456c78cfdf57bacb625db1b3fae30d3a/recovery/root/vendor/etc/vintf/manifest/vendor.mediatek.hardware.dplanner%402.0-service.xml#L1)

so i delete them like the .old one and missing file

**Comment by Harlock1978** [comment]
There is something I don't understand, reading [File-Based Encryption](https://source.android.com/docs/security/features/encryption/file-based) I found that also vold is important for encryption and I wanted to add it, but when I open init.rc in the mounted img there are some line about vold when I copy it to my Hd a cannot find them.

Problem solved I copy all the content on a new created file and now everything is inside, but I'm wondering where to add the line about vold, I think init.recovery.mt6873.rc, am I right?
[init.zip](https://github.com/Harlock1978/Armor_11_5G/files/10127757/init.zip)

**Comment by lopestom** [comment]
> There is something I don't understand, reading [File-Based Encryption](https://source.android.com/docs/security/features/encryption/file-based) I found that also vold is important for encryption and I wanted to add it, but when I open init.rc in the mounted img there are some line about vold when I copy it to my Hd a cannot find them.

The vold is related to that is made from TWRP source code. 

> Problem solved I copy all the content on a new created file and now everything is inside, but I'm wondering where to add the line about vold, I think init.recovery.mt6873.rc, am I right? [init.zip]
(https://github.com/Harlock1978/Armor_11_5G/files/10127757/init.zip)

Reference: https://github.com/TeamWin/android_bootable_recovery/tree/android-10.0/crypto/vold_decrypt
Again this is not need since vold is placed in the TWRP source code.

If you unpack TWRP.img and read the init.rc file vs stock init.rc so u need understand about Android System booting and the [TWRP as a separate OS. Structure, working principles, main components.](https://4pda.to/forum/index.php?s=&showtopic=964238&view=findpost&p=88433302). So the TWRP need the init.rc to booting your ow "system".
You only change/modify init.rc if have something OEM related in that. Generally not have.

**Comment by Harlock1978** [comment]
Ok I deleted the two vold files, then I think everything is fine and ready to be compiled.

**Comment by lopestom** [comment]
> Ok I deleted the two vold files, then I think everything is fine and ready to be compiled.

You can compile in your ow Linux PC or online following the compilation of the img file.
Compilation: https://github.com/lopestom/Action-Recovery-Builder-CT/actions/runs/3593752399/jobs/6051114421

If compilation good and have img file relesead here: https://github.com/lopestom/Action-Recovery-Builder-CT/releases

These way only can work if DT is public so not work if DT is private. Therefore your decision.

**Comment by Harlock1978** [comment]
I made my DT public, but I cannot start the process again.

I create a clone for me to run the recovery

**Comment by Harlock1978** [comment]
By the way this is the file I used to try to inject adbkey in my telephone:

[adbkey-signed.zip](https://github.com/Harlock1978/Armor_11_5G/files/10136680/adbkey-signed.zip)

To let this file working I create a new copy of the official recovery where I changed otacerts with the test key that is used by sign-em-anywhere_3.0.160204

**Comment by Harlock1978** [comment]
I try to compile the file online, but I always receive an error:

> fatal: cannot obtain manifest https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git
> manifests:
> fatal: couldn't find remote ref refs/heads/twrp-10.0-deprecated
> manifests: sleeping 4.0 seconds before retrying
> manifests:
> fatal: couldn't find remote ref refs/heads/twrp-10.0-deprecated
> Error: Process completed with exit code 1.

**Comment by lopestom** [comment]
> By the way this is the file I used to try to inject adbkey in my telephone:
> 
> [adbkey-signed.zip](https://github.com/Harlock1978/Armor_11_5G/files/10136680/adbkey-signed.zip)
> 
> To let this file working I create a new copy of the official recovery where I changed otacerts with the test key that is used by sign-em-anywhere_3.0.160204

I not know NOW what's the reason for using that file.
The first objective: starting Custom Recovery in your device. The img file booted? Y / N?!!

**Comment by lopestom** [comment]
> 

Simple!! If you want compiling with omni-10 use this: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni
branch: twrp-10.0-deprecated

But if you want compiling with twrp-11 use this: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp
branch: twrp-11
But before compiling you need change `omni_` to `twrp_` in all files that have.

**Comment by lopestom** [comment]
> I try to compile the file online, but I always receive an error:
> 
> > fatal: cannot obtain manifest https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git
> > manifests:
> > fatal: couldn't find remote ref refs/heads/twrp-10.0-deprecated
> > manifests: sleeping 4.0 seconds before retrying
> > manifests:
> > fatal: couldn't find remote ref refs/heads/twrp-10.0-deprecated
> > Error: Process completed with exit code 1.

Start compiling a time ago again and error appears:
`vendor/omni/build/tasks/dtbo.mk:22: error: writing to readonly directory: "device/ulefone/Armor_11_5G/prebuilt/dtbo.img"`

Updated DT with Hide:
```
The kernel in the A10 img file is not separated.
Hiding BOARD_KERNEL_SEPARATED_DTBO := true
```

Started new building: https://github.com/lopestom/Action-Recovery-Builder-CT/actions/runs/3603083991/jobs/6070837284

**Comment by lopestom** [comment]
img released: https://github.com/lopestom/Action-Recovery-Builder-CT/releases/tag/3603083991

**Comment by Harlock1978** [comment]
Thank you

I installed it and tried to lauch it, but it doesn't work/ Black screen and then reboot.

With the command fastboot boot recovery.img I get this error:

> Sending 'boot.img' (32768 KB)                      OKAY [  0.715s]
> Booting                                            FAILED (Status read failed (Too many links))

**Comment by Harlock1978** [comment]
Is there a way I can debug the recovery to see what lead to the crash and reboot?

**Comment by lopestom** [comment]
> 

You installed vbmeta modified file?
Download [vbmeta.img](https://dl.google.com/developers/android/qt/images/gsi/vbmeta.img?hl=en-us) with fastboot:
`fastboot --disable-verity --disable-verification flash vbmeta vbmeta.img`

After install TWRP.img and verify.
`fastboot flash recovery recovery.img`

 fastboot boot recovery.img NOT work for your device!!

**Comment by Harlock1978** [comment]
> You installed vbmeta modified file?

Yes

And your recovery is working showing some error, so there is something wrong in mine.

> fastboot boot recovery.img NOT work for your device!!

Yes I only later realised that it work only for A/B slot and I don't have it

**Comment by lopestom** [comment]
> 

My recovery??
The img file is from your DT so your file!

All tests need your device and your time. I haven't the same device.

Other question about https://github.com/Harlock1978/Armor_11_5G/blob/84b64c4538a305b7a3b28cb68b1553aabda4ab21/BoardConfig.mk#L126

Where's that from? I never put that.

Errors?! About not mount \system or \system_root or \vendor?
Y: Thats normal because in A10 and up the Super partition and logical partitions have ro mode.
If you want Read & Write these partitions so you need RW patch from xda: [[[SCRIPT][Android 10+] Universal MakeSystemRW Mount SystemRW / SuperRW featuring MakeRW (read/write)](https://forum.xda-developers.com/t/script-android-10-universal-makesystemrw-mount-systemrw-superrw-featuring-makerw-read-write.4247311/unread)](https://forum.xda-developers.com/t/script-android-10-universal-makesystemrw-mount-systemrw-superrw-featuring-makerw-read-write.4247311/unread)

N: Show errors.

**Comment by Harlock1978** [comment]
> My recovery??

I mean the recovery you created for 4pda that you give me the link.

> All tests need your device and your time

I know and I'm doing it, I planned a whole day off tomorrow only for that.

> Errors?! About not mount \system or \system_root or \vendor?

About nont founding cryptofooter and not be able to mount data.

> Other question about
> 
> [Armor_11_5G/BoardConfig.mk](https://github.com/Harlock1978/Armor_11_5G/blob/84b64c4538a305b7a3b28cb68b1553aabda4ab21/BoardConfig.mk#L126)
> 
> Line 126 in [84b64c4](https://github.com/Harlock1978/Armor_11_5G/commit/84b64c4538a305b7a3b28cb68b1553aabda4ab21)
> 
> 126  # Verified Boot 

> Where's that from? I never put that.
> 

It was created at the beginning by [twrpdtgen](https://github.com/twrpdtgen/twrpdtgen) and I didn't change it

**Comment by Harlock1978** [comment]
I try to change the fstab file in case is here the problem, but I cannot build the recovery I always receive an error.

Error:

> build/make/core/product_config.mk:223: error: Can not locate config makefile for product "omni_Armor_11_5G.mk"

**Comment by lopestom** [comment]
> I try to change the fstab file in case is here the problem, but I cannot build the recovery I always receive an error.
> 
> Error:
> 
> > build/make/core/product_config.mk:223: error: Can not locate config makefile for product "omni_Armor_11_5G.mk"

You not specified correctly the problem.

**Comment by lopestom** [comment]
> > My recovery??
> 
> I mean the recovery you created for 4pda that you give me the link.

I didn't know you got the file.
 
> I know and I'm doing it, I planned a whole day off tomorrow only for that.

> About nont founding cryptofooter and not be able to mount data.

I tried enabling encryption at the time. But unfortunately there must be something else that me and another user (who now has the same situation) couldn't get that.
So in this DT he show encrypt/decrypt working: https://github.com/ADeadTrousers/twrp_device_Unihertz_Atom_LXL/tree/twrp-10.0

But Armor 11 5G has this files too: https://github.com/ADeadTrousers/twrp_device_Unihertz_Atom_LXL/blob/03075080a3d038d770cc2f21dd8c046b809e1f32/proprietary-files.txt
```
vendor/bin/kph:recovery/root/vendor/bin/kph
vendor/bin/pld:recovery/root/vendor/bin/pld
```
 
> It was created at the beginning by [twrpdtgen](https://github.com/twrpdtgen/twrpdtgen) and I didn't change it

Okay. I'll put the correct.
-------------------------
Upd: Owwww. I not remembered it's about MT6873.

Not remember if 4096 is better than 2048.
But you can try:
```
# AVB
BOARD_AVB_ENABLE := true
BOARD_AVB_VBMETA_SYSTEM := system product
BOARD_AVB_VBMETA_SYSTEM_KEY_PATH := external/avb/test/data/testkey_rsa2048.pem
BOARD_AVB_VBMETA_SYSTEM_ALGORITHM := SHA256_RSA2048
BOARD_AVB_VBMETA_SYSTEM_ROLLBACK_INDEX := $(PLATFORM_SECURITY_PATCH_TIMESTAMP)
BOARD_AVB_VBMETA_SYSTEM_ROLLBACK_INDEX_LOCATION := 1
BOARD_AVB_VBMETA_VENDOR := vendor
BOARD_AVB_VBMETA_VENDOR_KEY_PATH := external/avb/test/data/testkey_rsa2048.pem
BOARD_AVB_VBMETA_VENDOR_ALGORITHM := SHA256_RSA2048
BOARD_AVB_VBMETA_VENDOR_ROLLBACK_INDEX := $(PLATFORM_SECURITY_PATCH_TIMESTAMP)
BOARD_AVB_VBMETA_VENDOR_ROLLBACK_INDEX_LOCATION := 2
BOARD_AVB_RECOVERY_KEY_PATH := external/avb/test/data/testkey_rsa2048.pem
BOARD_AVB_RECOVERY_ALGORITHM := SHA256_RSA2048
BOARD_AVB_RECOVERY_ROLLBACK_INDEX := $(PLATFORM_SECURITY_PATCH_TIMESTAMP)
BOARD_AVB_RECOVERY_ROLLBACK_INDEX_LOCATION := 3

# DECRYPTION
BOARD_AVB_RECOVERY_ADD_HASH_FOOTER_ARGS += \
    --prop com.android.build.boot.os_version:$(PLATFORM_VERSION) \
    --prop com.android.build.boot.security_patch:$(PLATFORM_SECURITY_PATCH)
```

If that's not good so back to 4096.

Remembering now about other MT6873 help but with A11: https://github.com/PizzaG/android_device_fih_EC211001/blob/b5309649520bd07deaf60278ce87bee0641eb46f/BoardConfig.mk#L210

**Comment by Harlock1978** [comment]
I will insert again verified boot in Boardconfig.mk and adding your suggestion, I will look for proprietary files in vendor like the one in the list and try to compare with the oher repository [https://github.com/ADeadTrousers/twrp_device_Unihertz_Atom_LXL/tree/twrp-10.0](url).

> You not specified correctly the problem.

When I try to run the script to create the recovery everything run fine up to Building recovery when I receive the error

build/make/core/product_config.mk:223: error: Can not locate config makefile for product "omni_Armor_11_5G.mk"

while in your build 

> WARNING: device/ulefone/Armor_11_5G/omni.dependencies file not found
> 
> ============================================
> PLATFORM_VERSION_CODENAME=REL
> PLATFORM_VERSION=10
> TARGET_PRODUCT=omni_Armor_11_5G
> TARGET_BUILD_VARIANT=eng
> .....

I'm adding some file in the list proprietary files, but there is one missing: 

> vendor/bin/tee_check_keybox

**Comment by Harlock1978** [comment]
I download the ROM for Atom L and I didn't find this file tee_check_keybox, I'm wondering if he wrote it or if it's a symlink or is just tee + some options.

Reading the repository I found it was added in latest vendor-update

**Comment by lopestom** [comment]
> I'm adding some file in the list proprietary files, but there is one missing:
> 
> > vendor/bin/tee_check_keybox

If that file not have so not need add....... This file a new enc_dec configuration that I wrote before. Without that configuration (file) so enc_dec worked. Maybe the company put this file on different devices, maybe some companies didn't put it, maybe that disturbs the enc_dec process... But what I know is that, after having this file, the enc_dec process stopped working.
But there is also the code update by TeamWin and even with that, I didn't make more TWRP files for testing. Users are using the process of encryptable (no password - no encryption).

**Comment by lopestom** [comment]
> > You not specified correctly the problem.
> 
> When I try to run the script to create the recovery everything run fine up to Building recovery when I receive the error
> 
> build/make/core/product_config.mk:223: error: Can not locate config makefile for product "omni_Armor_11_5G.mk"
> 
> while in your build
> 
> > WARNING: device/ulefone/Armor_11_5G/omni.dependencies file not found
> > ============================================
> > PLATFORM_VERSION_CODENAME=REL
> > PLATFORM_VERSION=10
> > TARGET_PRODUCT=omni_Armor_11_5G
> > TARGET_BUILD_VARIANT=eng
> > .....

Always show me the correct errors like your ow Actions Build:
``` Sync Device Dependencies
Run bash ${GITHUB_WORKSPACE}/scripts/convert.sh device/ulefone/Armor_[1](https://github.com/Harlock1978/Action-Recovery-Builder-CT/actions/runs/3622586246/jobs/6107476735#step:14:1)1_5G/omni.dependencies
  bash ${GITHUB_WORKSPACE}/scripts/convert.sh device/ulefone/Armor_11_5G/omni.dependencies
  repo sync -j$(nproc --all)
  shell: /bin/bash -e {0}
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java_Zulu_jdk/8.0.35[2](https://github.com/Harlock1978/Action-Recovery-Builder-CT/actions/runs/3622586246/jobs/6107476735#step:14:2)-8/x64
    JAVA_HOME_8_X64: /opt/hostedtoolcache/Java_Zulu_jdk/8.0.[3](https://github.com/Harlock1978/Action-Recovery-Builder-CT/actions/runs/3622586246/jobs/6107476735#step:14:3)52-8/x6[4](https://github.com/Harlock1978/Action-Recovery-Builder-CT/actions/runs/3622586246/jobs/6107476735#step:14:4)
 ** Input File : device/ulefone/Armor_11_[5](https://github.com/Harlock1978/Action-Recovery-Builder-CT/actions/runs/3622586246/jobs/6107476735#step:14:5)G/omni.dependencies does not exist
 ** Please specify the correct dependencies file
 ** Usage : bash <path-to-script> <path-to-dependencies-file> [<path-to-local-manifest>]
Error: Process completed with exit code 1.
```

``` Building Recovery
Run source build/envsetup.sh
  source build/envsetup.sh
  export ALLOW_MISSING_DEPENDENCIES=true
  lunch omni_Armor_11_5G.mk-eng && make clean && make recoveryimage -j$(nproc --all)
  shell: /bin/bash -e {0}
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java_Zulu_jdk/8.0.35[2](https://github.com/Harlock1978/Action-Recovery-Builder-CT/actions/runs/3622586246/jobs/6107476735#step:16:2)-8/x64
    JAVA_HOME_8_X64: /opt/hostedtoolcache/Java_Zulu_jdk/8.0.[3](https://github.com/Harlock1978/Action-Recovery-Builder-CT/actions/runs/3622586246/jobs/6107476735#step:16:3)52-8/x6[4](https://github.com/Harlock1978/Action-Recovery-Builder-CT/actions/runs/3622586246/jobs/6107476735#step:16:4)
including device/ulefone/Armor_11_[5](https://github.com/Harlock1978/Action-Recovery-Builder-CT/actions/runs/3622586246/jobs/6107476735#step:16:5)G/vendorsetup.sh
ccache found and CCACHE_EXEC has been set to : /usr/bin/ccache
build/make/core/product_config.mk:223: error: Can not locate config makefile for product "omni_Armor_11_5G.mk".
18:00:4[6](https://github.com/Harlock1978/Action-Recovery-Builder-CT/actions/runs/3622586246/jobs/6107476735#step:16:6) dumpvars failed with: exit status 1
Traceback (most recent call last):
Your device can't be found in device sources..
  File "vendor/omni/build/tools/roomservice.py", line 41[7](https://github.com/Harlock1978/Action-Recovery-Builder-CT/actions/runs/3622586246/jobs/6107476735#step:16:7), in <module>
    fetch_device(device)
  File "vendor/omni/build/tools/roomservice.py", line 3[8](https://github.com/Harlock1978/Action-Recovery-Builder-CT/actions/runs/3622586246/jobs/6107476735#step:16:8)5, in fetch_device
    git_data = search_gerrit_for_device(device)
  File "vendor/omni/build/tools/roomservice.py", line 81, in search_gerrit_for_device
    device_data = check_repo_exists(git_data, device)
  File "vendor/omni/build/tools/roomservice.py", line 58, in check_repo_exists
    "exiting roomservice".format(device=device))
Exception: Armor_[11](https://github.com/Harlock1978/Action-Recovery-Builder-CT/actions/runs/3622586246/jobs/6107476735#step:16:12)_5G.mk not found,exiting roomservice
build/make/core/product_config.mk:223: error: Can not locate config makefile for product "omni_Armor_11_5G.mk".
[18](https://github.com/Harlock1978/Action-Recovery-Builder-CT/actions/runs/3622586246/jobs/6107476735#step:16:19):00:47 dumpvars failed with: exit status 1

** Don't have a product spec for: 'omni_Armor_11_5G.mk'
** Do you have the right repo manifest?

Error: Process completed with exit code 1.
```

I cannot look any errors because the Actions Settings is good.
Maybe Settings for `Personal access tokens` or `Actions secrets` is wrong or nothing??

**Comment by lopestom** [comment]
Adc [omni.dependencies](https://github.com/Harlock1978/Armor_11_5G/blob/master/omni.dependencies) for Building Recovery.

How the Issue list was completed and now have minor issues so i'll close that and you can open new.
